[
  {name: 'トップス', categories_id: 1 },
  {name: 'ジャケット/アウター', categories_id: 1 },
  {name: 'パンツ', categories_id: 1 },
  {name: 'スカート', categories_id: 1 },
  {name: 'ワンピース', categories_id: 1 },
  {name: '靴', categories_id: 1 },
  {name: 'ルームウェア/パジャマ', categories_id: 1 },
  {name: 'レッグウェア', categories_id: 1 },
  {name: '帽子', categories_id: 1 },
  {name: 'バッグ', categories_id: 1 },
  {name: 'アクセサリー', categories_id: 1 },
  {name: 'ヘアアクセサリー', categories_id: 1 },
  {name: '小物', categories_id: 1 },
  {name: '時計', categories_id: 1 },

  {name: 'トップス', categories_id: 2 },
  {name: 'ジャケット/アウター', categories_id: 2 },
  {name: 'パンツ', categories_id: 2 },
  {name: '靴', categories_id: 2 },
  {name: 'バッグ', categories_id: 2 },
  {name: 'スーツ', categories_id: 2 },
  {name: '帽子', categories_id: 2 },
  {name: 'アクセサリー', categories_id: 2 },
  {name: '小物', categories_id: 2 },
  {name: '時計', categories_id: 2 },
  {name: '水着', categories_id: 2 },
  {name: 'レッグウェア', categories_id: 2 },
  {name: 'アンダーウェア', categories_id: 2 },
  {name: 'その他', categories_id: 2 },

  {name: 'ベビー服(女の子用) ~95cm', categories_id: 3 },
  {name: 'ベビー服(男の子用) ~95cm', categories_id: 3 },
  {name: 'ベビー服(男女兼用) ~95cm', categories_id: 3 },
  {name: 'キッズ服(女の子用) 100cm~', categories_id: 3 },
  {name: 'キッズ服(男の子用) 100cm~', categories_id: 3 },
  {name: 'キッズ服(男女兼用) 100cm~', categories_id: 3 },
  {name: 'キッズ靴', categories_id: 3 },
  {name: '子ども用ファッション小物', categories_id: 3 },
  {name: 'おむつ/トイレ/バス', categories_id: 3 },
  {name: '外出/移動用品', categories_id: 3 },
  {name: '授乳/食事', categories_id: 3 },
  {name: 'ベビー家具/寝具/室内用品', categories_id: 3 },
  {name: 'おもちゃ', categories_id: 3 },
  {name: '行事/記念品', categories_id: 3 },

  {name: 'キッチン/食器', categories_id: 4 },
  {name: 'ベッド/マットレス', categories_id: 4 },
  {name: 'ソファ/ソファベッド', categories_id: 4 },
  {name: '椅子/チェア', categories_id: 4 },
  {name: '机/テーブル', categories_id: 4 },
  {name: '収納家具', categories_id: 4 },
  {name: 'ラグ/カーペット/マット', categories_id: 4 },
  {name: 'カーテン/ブラインド', categories_id: 4 },
  {name: 'ライト/照明', categories_id: 4 },
  {name: '寝具', categories_id: 4 },
  {name: 'インテリア小物', categories_id: 4 },
  {name: '季節/年中行事', categories_id: 4 },
  {name: 'その他', categories_id: 4 },

  {name: '本', categories_id: 5 },
  {name: '漫画', categories_id: 5 },
  {name: '雑誌', categories_id: 5 },
  {name: 'CD', categories_id: 5 },
  {name: 'DVD/ブルーレイ', categories_id: 5 },
  {name: 'レコード', categories_id: 5 },
  {name: 'テレビゲーム', categories_id: 5 },

  {name: 'おもちゃ', categories_id: 6 },
  {name: 'タレントグッズ', categories_id: 6 },
  {name: 'コミック/アニメグッズ', categories_id: 6 },
  {name: 'トレーディングカード', categories_id: 6 },
  {name: 'フィギュア', categories_id: 6 },
  {name: '楽器/器材', categories_id: 6 },
  {name: 'コレクション', categories_id: 6 },
  {name: 'ミリタリー', categories_id: 6 },
  {name: '美術品', categories_id: 6 },
  {name: 'アート用品', categories_id: 6 },
  {name: 'その他', categories_id: 6 },

  {name: 'ベースメイク', categories_id: 7 },
  {name: 'メイクアップ', categories_id: 7 },
  {name: 'ネイルケア', categories_id: 7 },
  {name: '香水', categories_id: 7 },
  {name: 'スキンケア/基礎化粧品', categories_id: 7 },
  {name: 'ヘアケア', categories_id: 7 },
  {name: 'ボディケア', categories_id: 7 },
  {name: 'オーラルケア', categories_id: 7 },
  {name: 'リラクゼーション', categories_id: 7 },
  {name: 'ダイエット', categories_id: 7 },
  {name: 'その他', categories_id: 7 },

  {name: 'スマートフォン/携帯電話', categories_id: 8 },
  {name: 'スマホアクセサリー', categories_id: 8 },
  {name: 'PC/タブレット', categories_id: 8 },
  {name: 'カメラ', categories_id: 8 },
  {name: 'テレビ/映像機器', categories_id: 8 },
  {name: 'オーディオ機器', categories_id: 8 },
  {name: '美容/健康', categories_id: 8 },
  {name: '冷暖房/空調', categories_id: 8 },
  {name: '生活家電', categories_id: 8 },
  {name: 'その他', categories_id: 8 },

  {name: 'ゴルフ', categories_id: 9 },
  {name: 'フィッシング', categories_id: 9 },
  {name: '自転車', categories_id: 9 },
  {name: 'トレーニング/エクササイズ', categories_id: 9 },
  {name: '野球', categories_id: 9 },
  {name: 'サッカー/フットサル', categories_id: 9 },
  {name: 'テニス', categories_id: 9 },
  {name: 'スノーボード', categories_id: 9 },
  {name: 'スキー', categories_id: 9 },
  {name: 'その他スポーツ', categories_id: 9 },
  {name: 'アウトドア', categories_id: 9 },
  {name: 'その他', categories_id: 9 },

  {name: 'アクセサリー(女性用)', categories_id: 10 },
  {name: 'ファッション/小物', categories_id: 10 },
  {name: 'アクセサリー/時計', categories_id: 10 },
  {name: '日用品/インテリア', categories_id: 10 },
  {name: '趣味/おもちゃ', categories_id: 10 },
  {name: 'キッズ/ベビー', categories_id: 10 },
  {name: '素材/材料', categories_id: 10 },
  {name: '二次創作物', categories_id: 10 },
  {name: 'その他', categories_id: 10 },

  {name: '音楽', categories_id: 11 },
  {name: 'スポーツ', categories_id: 11 },
  {name: '演劇/芸能', categories_id: 11 },
  {name: 'イベント', categories_id: 11 },
  {name: '映画', categories_id: 11 },
  {name: '施設利用券', categories_id: 11 },
  {name: '優待券/割引券', categories_id: 11 },
  {name: 'その他', categories_id: 11 },

  {name: '自動車本体', categories_id: 12 },
  {name: '自動車タイヤ/ホイール', categories_id: 12 },
  {name: '自動車パーツ', categories_id: 12 },
  {name: '自動車アクセサリー', categories_id: 12 },
  {name: 'オートバイ車体', categories_id: 12 },
  {name: 'オートバイパーツ', categories_id: 12 },
  {name: 'オートバイアクセサリー', categories_id: 12 },

  {name: 'まとめ売り', categories_id: 13 },
  {name: 'ペット用品', categories_id: 13 },
  {name: '食品', categories_id: 13 },
  {name: '飲料/酒', categories_id: 13 },
  {name: '日用品/生活雑貨/旅行', categories_id: 13 },
  {name: 'アンティーク/コレクション', categories_id: 13 },
  {name: '文房具/事務用品', categories_id: 13 },
  {name: '事務/店舗用品', categories_id: 13 },
  {name: 'その他', categories_id: 13 }

].each do |d|
  data = ChildCategory.create(name: d[:name], categories_id: d[:categories_id])

  data.name = d[:name]
  data.categories_id = d[:categories_id]
  data.save

end
